### ISSUE TITLE
NameError: name 'django' is not defined

### ISSUE THREAD

**Issue by SamanShafigh** [lrcry/ExpertMind#1]
Hi 

When I run this project I get this error. I think it is from django_stormpath. Do I have to do any extra configuration. Thanks 

➜ ExpertMind git:(master) sudo docker run -p 81:8000 expert-mind
Already up-to-date.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.**dict**[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in **get**
    res = instance.**dict**[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/service/urls.py", line 18, in <module>
    import django_stormpath.urls
  File "/usr/local/lib/python2.7/site-packages/django_stormpath/urls.py", line 44, in <module>
    if django.VERSION[:2] < (1, 8):
NameError: name 'django' is not defined

**Comment by SamanShafigh** [comment]
Thanks, I fixed it. It was an issue about django_stormpath so I just simply commented out that part so still I can work with system which is nice but without authentication part which is Ok

**Comment by lrcry** [comment]
G'day @SamanShafigh ,

Glad to hear that you've solved the problem!

Hope you enjoy it as it has been a long time since we worked for this project last time. We would like to try to keep it going hopefully.

Cheers,

Hans Mong
